### ISSUE TITLE
APIGenerator NPE

### ISSUE THREAD

**Issue by leotu** [Netflix/hollow#19] opened 2017-02-13 08:51 UTC
how.hollow.consumer.api.APIGenerator.java occur NPE when listFiles return null value.
(apiCodeFolder doen't exist)

```java
for(File f : apiCodeFolder.listFiles())
     f.delete();
```

maybe add some code like this
```java
if (!apiCodeFolder.exists()) {
     apiCodeFolder.mkdirs();
}
```

Sorry, this issue is not on this project, I posted on wrong project :-),  pls invalid it!

**Comment by dkoszewnik** [comment] 2017-02-17 01:11
Duplicate of https://github.com/Netflix/hollow-reference-implementation/issues/4

**Closed as completed by dkoszewnik** 2017-02-17 01:11 UTC
