### ISSUE TITLE
Unexpected/incorrect callback order for HollowConsumer.RefreshListener during init

### ISSUE THREAD

**Issue by brettwooldridge** [Netflix/hollow#80] opened 2017-08-16 06:41 UTC
We have a ``RefreshListener`` registered with the ``HollowConsumer``.  We are implementing ``snapshotUpdateOccurred()`` and ``deltaUpdateOccurred()``, whereby we act upon add/modify/delete of objects based on the ``populatedOrdinals``/``previousOrdinals``.

When starting from a clean state (no objects in hollow), everything works as expected.  The server produces a snapshot and announces it, then the client processes it and calls ``snapshotUpdateOccurred()``.  The next change on the server produces a delta, which is announced, and the client processes it and calls ``deltaUpdateOccurred()``.  So far, so good.

The trouble occurs when we restart the client.

We construct the ``HollowConsumer`` and call ``triggerAsyncRefresh()``.  In order to restore the state from the locally persisted files, the consumer ends up calling ``HollowDataHolder.applyInitialTransitions()``.  [That method](https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/client/HollowDataHolder.java#L97) ends up applying all of the transitions, starting with the snapshot then proceeding through the deltas, and only after all of that [calls ``snapshotUpdateOccurred()``](https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/client/HollowDataHolder.java#L120) with the *final* version arrived at (which is actually a delta, not a snapshot, btw).

At that point, we have missed our chance to process the transitions via ``populatedOrdinals``/``previousOrdinals``, because the ``previousOrdinals`` only contains those of the final transition.

What we *need* is for the ``RefreshListener`` to be called for each transition, just as if they were occurring at runtime.

**Comment by dkoszewnik** [comment] 2017-08-16 21:45
Hi @brettwooldridge, this is actually the intended behavior.

The `snapshotUpdateOccurred()` method is used to indicate that a refresh which began with a snapshot has completed successfully.  A refresh can include multiple transitions.  From the javadocs:

> This method is called when either data was initialized for the first time, <i>or</i> an update occurred across a discontinuous delta chain (double snapshot).
>
> Implementations should initialize (or re-initialize) any indexing which is critical to keep in-sync with the data.
>
> If this method is called, it means that the current refresh consists of a snapshot load, plus zero or more deltas. 
>
> This method will be called a maximum of once per refresh, after the data has reached the final state of the refresh.

The behavior you're looking for is instead available via the [`blobLoaded(HollowConsumer.Blob blob)`](https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/consumer/HollowConsumer.java#L550) method (you can determine whether or not the blob loaded was a snapshot using `blob.isSnapshot()`).

Unfortunately we (and perhaps others) already rely on the distinction between these two methods, and changing the behavior as proposed would break backwards compatibility.

During the development of the `HollowConsumer` API, we did have some conversations around whether or not this distinction was clear enough -- but perhaps landed on the wrong side here.  We're definitely open to suggestions about better verbiage in the comments of these methods, or even clearer method names -- as long as we deprecate the existing methods and leave both versions available and functional until a major version release.

**Comment by brettwooldridge** [comment] 2017-08-17 00:23
We are aware of the ``blobLoaded()`` callback.  Here's the problem.

This is what our callbacks look like (code in Kotlin):
```kotlin
override fun snapshotUpdateOccurred(api : HollowAPI, stateEngine : HollowReadStateEngine, version : Long) {
   // create indexes
   monitorIndex = HollowPrimaryKeyIndex(stateEngine, "Monitor", "monitorId")
   ...

   // process changes
   processChanges(api, stateEngine)
}

override fun deltaUpdateOccurred(api : HollowAPI, stateEngine : HollowReadStateEngine, version : Long) {
   // process changes
   processChanges(api, stateEngine)
}

private fun processChanges(api : HollowAPI, stateEngine : HollowReadStateEngine) {
   // uses the HollowAPI to calculate add/modify/remove and act on those changes
}
```
When the state is being reinitialized by ``HollowDataHolder.applyInitialTransitions()``, we cannot use the ``blobLoaded(HollowConsumer.Blob blob)`` callback because we have *no access* to the API at that point (and it looks as though the API is not even constructed at that point).

What exactly was the reasoning behind the original design decision?  If the callback pattern is the same, whether as a result of runtime behavior or reinitialization behavior, the implementation can be identical.  But due to this design decision different code paths must be implemented (were it even possible, which at this point it is not).  Working with Hollow and calculating change sets etc. is not exactly trivial, and having to implement different handling and code paths substantially increases the number of unit tests required to verify those paths.

**Comment by brettwooldridge** [comment] 2017-08-17 00:53
As a side note, as the author and maintainer of a project used by millions of developers (no hyperbole), [HikariCP](https://github.com/brettwooldridge/HikariCP), I know well that we sometimes make design decisions that in hindsight prove to be incorrect.  I've made them, we all make them, and while unfortunate and regrettable, it is far better to correct them than to simply work around them or carry them forward.  Accounting for that is the purpose of semantic versioning.  A change from 2.x to 3.x would indicate incompatible API changes.

**Comment by dkoszewnik** [comment] 2017-08-17 23:06
Thanks for the clarification.  I missed the fact that access to the API was not provided in the `blobLoaded()` callback -- and that you need that for your use case.

I like the approach you took to preserve backwards compatibility in #82, thank you.  We are aware of the mechanics of semver but we have a few minor backwards incompatible changes we'd also like to bundle in a `v3.0.0` release, which we're not currently ready for.

I did make some modifications to #82 to address object longevity and protect both sets of callback methods with a unit test.  Please take a quick look to confirm that these also match your expectations.  I'd also like to solicit at least one more review from our side, and then we can merge and release this.

Thanks again,
Drew.

**Closed as completed** 2017-08-18 18:16 UTC

**Comment by brettwooldridge** [comment] 2017-08-19 02:13
@dkoszewnik Thanks.
